/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Group } from './V1Group';
import {
    V1GroupFromJSON,
    V1GroupFromJSONTyped,
    V1GroupToJSON,
} from './V1Group';

/**
 * 
 * @export
 * @interface V1Groups
 */
export interface V1Groups {
    /**
     * 
     * @type {Array<V1Group>}
     * @memberof V1Groups
     */
    groups?: Array<V1Group>;
}

/**
 * Check if a given object implements the V1Groups interface.
 */
export function instanceOfV1Groups(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GroupsFromJSON(json: any): V1Groups {
    return V1GroupsFromJSONTyped(json, false);
}

export function V1GroupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Groups {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groups': !exists(json, 'groups') ? undefined : ((json['groups'] as Array<any>).map(V1GroupFromJSON)),
    };
}

export function V1GroupsToJSON(value?: V1Groups | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groups': value.groups === undefined ? undefined : ((value.groups as Array<any>).map(V1GroupToJSON)),
    };
}

