/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Group
 */
export interface V1Group {
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1Group
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Group
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    groupName?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Group
     */
    weight?: number;
}

/**
 * Check if a given object implements the V1Group interface.
 */
export function instanceOfV1Group(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GroupFromJSON(json: any): V1Group {
    return V1GroupFromJSONTyped(json, false);
}

export function V1GroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Group {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'groupName': !exists(json, 'group_name') ? undefined : json['group_name'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
    };
}

export function V1GroupToJSON(value?: V1Group | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'group_name': value.groupName,
        'weight': value.weight,
    };
}

