/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1OptionDefinition } from './V1OptionDefinition';
import {
    V1OptionDefinitionFromJSON,
    V1OptionDefinitionFromJSONTyped,
    V1OptionDefinitionToJSON,
} from './V1OptionDefinition';

/**
 * 
 * @export
 * @interface V1OptionDefinitions
 */
export interface V1OptionDefinitions {
    /**
     * 
     * @type {Array<V1OptionDefinition>}
     * @memberof V1OptionDefinitions
     */
    optionDefinitions?: Array<V1OptionDefinition>;
}

/**
 * Check if a given object implements the V1OptionDefinitions interface.
 */
export function instanceOfV1OptionDefinitions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1OptionDefinitionsFromJSON(json: any): V1OptionDefinitions {
    return V1OptionDefinitionsFromJSONTyped(json, false);
}

export function V1OptionDefinitionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1OptionDefinitions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'optionDefinitions': !exists(json, 'optionDefinitions') ? undefined : ((json['optionDefinitions'] as Array<any>).map(V1OptionDefinitionFromJSON)),
    };
}

export function V1OptionDefinitionsToJSON(value?: V1OptionDefinitions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'optionDefinitions': value.optionDefinitions === undefined ? undefined : ((value.optionDefinitions as Array<any>).map(V1OptionDefinitionToJSON)),
    };
}

