/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1OptionValueResponse
 */
export interface V1OptionValueResponse {
    /**
     * 
     * @type {string}
     * @memberof V1OptionValueResponse
     */
    optionValue?: string;
}

/**
 * Check if a given object implements the V1OptionValueResponse interface.
 */
export function instanceOfV1OptionValueResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1OptionValueResponseFromJSON(json: any): V1OptionValueResponse {
    return V1OptionValueResponseFromJSONTyped(json, false);
}

export function V1OptionValueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1OptionValueResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'optionValue': !exists(json, 'option_value') ? undefined : json['option_value'],
    };
}

export function V1OptionValueResponseToJSON(value?: V1OptionValueResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'option_value': value.optionValue,
    };
}

