/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1OptionType = {
    Boolean: 'OPTION_TYPE_BOOLEAN',
    Text: 'OPTION_TYPE_TEXT',
    Integer: 'OPTION_TYPE_INTEGER',
    Float: 'OPTION_TYPE_FLOAT',
    Date: 'OPTION_TYPE_DATE',
    Time: 'OPTION_TYPE_TIME',
    Enum: 'OPTION_TYPE_ENUM',
    Json: 'OPTION_TYPE_JSON',
    Bytes: 'OPTION_TYPE_BYTES'
} as const;
export type V1OptionType = typeof V1OptionType[keyof typeof V1OptionType];


export function V1OptionTypeFromJSON(json: any): V1OptionType {
    return V1OptionTypeFromJSONTyped(json, false);
}

export function V1OptionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1OptionType {
    return json as V1OptionType;
}

export function V1OptionTypeToJSON(value?: V1OptionType | null): any {
    return value as any;
}

