/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Group } from './V1Group';
import {
    V1GroupFromJSON,
    V1GroupFromJSONTyped,
    V1GroupToJSON,
} from './V1Group';

/**
 * 
 * @export
 * @interface V1UpsertGroupsRequest
 */
export interface V1UpsertGroupsRequest {
    /**
     * 
     * @type {Array<V1Group>}
     * @memberof V1UpsertGroupsRequest
     */
    groups?: Array<V1Group>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpsertGroupsRequest
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the V1UpsertGroupsRequest interface.
 */
export function instanceOfV1UpsertGroupsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpsertGroupsRequestFromJSON(json: any): V1UpsertGroupsRequest {
    return V1UpsertGroupsRequestFromJSONTyped(json, false);
}

export function V1UpsertGroupsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpsertGroupsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groups': !exists(json, 'groups') ? undefined : ((json['groups'] as Array<any>).map(V1GroupFromJSON)),
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
    };
}

export function V1UpsertGroupsRequestToJSON(value?: V1UpsertGroupsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groups': value.groups === undefined ? undefined : ((value.groups as Array<any>).map(V1GroupToJSON)),
        'fields': value.fields,
    };
}

