/* tslint:disable */
/* eslint-disable */
/**
 * sprinkles/v1/api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1OptionDefinition } from './V1OptionDefinition';
import {
    V1OptionDefinitionFromJSON,
    V1OptionDefinitionFromJSONTyped,
    V1OptionDefinitionToJSON,
} from './V1OptionDefinition';

/**
 * 
 * @export
 * @interface V1UpsertOptionDefinitionsRequest
 */
export interface V1UpsertOptionDefinitionsRequest {
    /**
     * 
     * @type {Array<V1OptionDefinition>}
     * @memberof V1UpsertOptionDefinitionsRequest
     */
    optionDefinitions?: Array<V1OptionDefinition>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpsertOptionDefinitionsRequest
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the V1UpsertOptionDefinitionsRequest interface.
 */
export function instanceOfV1UpsertOptionDefinitionsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpsertOptionDefinitionsRequestFromJSON(json: any): V1UpsertOptionDefinitionsRequest {
    return V1UpsertOptionDefinitionsRequestFromJSONTyped(json, false);
}

export function V1UpsertOptionDefinitionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpsertOptionDefinitionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'optionDefinitions': !exists(json, 'optionDefinitions') ? undefined : ((json['optionDefinitions'] as Array<any>).map(V1OptionDefinitionFromJSON)),
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
    };
}

export function V1UpsertOptionDefinitionsRequestToJSON(value?: V1UpsertOptionDefinitionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'optionDefinitions': value.optionDefinitions === undefined ? undefined : ((value.optionDefinitions as Array<any>).map(V1OptionDefinitionToJSON)),
        'fields': value.fields,
    };
}

